"""Add type and city.

Revision ID: 13a898358191
Revises: da51512f238c
Create Date: 2023-09-21 15:38:55.388761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a898358191'
down_revision: Union[str, None] = 'da51512f238c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('city', sa.String(length=250), nullable=True))
    op.add_column('events', sa.Column('event_type', sa.String(length=250), nullable=True))
    op.alter_column('events', 'desc',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'desc',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'city')
    # ### end Alembic commands ###
