"""Add user names.

Revision ID: 3e6bac65c5f6
Revises: 13a898358191
Create Date: 2023-09-22 14:11:24.043987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6bac65c5f6'
down_revision: Union[str, None] = '13a898358191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('org_name', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'org_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
